@echo off
copy graphim.pas  c:\program\tp7\bin\sorce\graphim\graphim.pas
copy install.pas  c:\program\tp7\bin\sorce\graphim\install.pas
copy mousebx.pas  c:\program\tp7\bin\sorce\graphim\mousebx.pas
copy bxdialog.pas c:\program\tp7\bin\sorce\graphim\bxdialog.pas
copy boxes.pas    c:\program\tp7\bin\sorce\graphim\boxes.pas
copy bituy.pas    c:\program\tp7\bin\sorce\graphim\bituy.pas
copy bituytst.pas c:\program\tp7\bin\sorce\graphim\bituytst.pas
copy draw_gr.pas  c:\program\tp7\bin\sorce\graphim\draw_gr.pas
copy udr_gr.pas   c:\program\tp7\bin\sorce\graphim\udr_gr.pas
copy event.pas    c:\program\tp7\bin\sorce\graphim\event.pas
copy app.pas      c:\program\tp7\bin\sorce\graphim\app.pas
copy mouse2.pas   c:\program\tp7\bin\sorce\graphim\mouse2.pas
copy general.pas  c:\program\tp7\bin\sorce\graphim\general.pas
copy help.pas     c:\program\tp7\bin\sorce\graphim\help.pas
copy helptest.pas c:\program\tp7\bin\sorce\graphim\helptest.pas
copy inifiles.pas c:\program\tp7\bin\sorce\graphim\inifiles.pas
copy menugr.pas   c:\program\tp7\bin\sorce\graphim\menugr.pas
copy menuproc.pas c:\program\tp7\bin\sorce\graphim\menuproc.pas
copy mousebx.pas  c:\program\tp7\bin\sorce\graphim\mousebx.pas
copy initiali.pas c:\program\tp7\bin\sorce\graphim\initiali.pas
copy set_gr.pas   c:\program\tp7\bin\sorce\graphim\set_gr.pas
copy stack.pas    c:\program\tp7\bin\sorce\graphim\stack.pas
copy usergr.pas   c:\program\tp7\bin\sorce\graphim\usergr.pas
copy graphim.hlp  c:\program\tp7\bin\sorce\graphim\graphim.hlp
copy c:\program\tp7\bin\execut\graphim.exe
copy c:\program\tp7\bin\execut\install.exe
