program builder;
{--------------------------------------}
{  Interface builder                   }
{     An attempt to make a program that}
{     build an interface and save it   }
{			into a unit that you can use in  }
{     programs.                        }
{--------------------------------------}
uses general,bapplic;

begin
	graphinit(2);
  initapp;
  runapp;
  byeapp;
end.


